# Generated by Django 6.0.7 on 2026-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_type',
            field=models.CharField(choices=[('python', 'python developer'), ('java', 'java developer'), ('web', 'web developement'), ('cyber', 'cybersecurity'), ('mobile', 'app development')], default='others', max_length=50),
            preserve_default=False,
        ),
    ]
